INSERT INTO animals (name, scientific_name, living_relative, period, status, continent, habitat, fun_fact, description, image_url, youtube_id) VALUES
('Dire Wolf', 'Aenocyon dirus', 'Gray Wolf / Domestic Dog', 'Pleistocene', 'DE_EXTINCT', 'North America', 'Forests and grasslands', 'The dire wolf was 25% heavier than a gray wolf with a stronger bite force built for crushing bone.', 'The dire wolf was one of the most iconic prehistoric predators. Larger and heavier than the modern gray wolf it roamed North America in packs. In 2025 scientists announced successful de-extinction efforts.', 'https://images.unsplash.com/photo-1564466809058-bf4114d55352?w=400&q=80', ''),

('Saber-tooth Cat', 'Smilodon fatalis', 'Lions, Tigers, House Cats', 'Pleistocene', 'EXTINCT', 'North America', 'Grasslands and forests', 'Despite its nickname saber-tooth tiger it was more closely related to modern lions than tigers.', 'The saber-tooth cat was a fearsome predator known for its enormous canine teeth that could reach 11 inches long. It used these teeth to deliver killing bites to large prey.', 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhSa8BISA4THN_cIzgbmFLenIRal93Ul6stmzTyIFbtvdraCN1unWU2VfOeWgR6RvwXNVWROAgkfs47jaF7foG6Zkz0PxqNTAaBLWcFYdt8HGBMU7wRziSqp_blh3gLNVnoPw7XB84_iVs/s1600/Smilodon2.jpg', ''),

('Woolly Mammoth', 'Mammuthus primigenius', 'African Elephant, Asian Elephant', 'Pleistocene', 'EXTINCT', 'Eurasia', 'Tundra and grasslands', 'Woolly mammoths had tusks that could grow up to 15 feet long and curved dramatically.', 'The woolly mammoth was a massive elephant species covered in thick fur to survive the ice age. They lived alongside early humans who hunted them for food and used their bones for shelter.', 'https://cdn.britannica.com/09/74609-050-21E14E52/Wooly-mammoth-replica-species-Canadian-extinct.jpg', ''),

('Dodo', 'Raphus cucullatus', 'Pigeons, Doves', 'Holocene', 'EXTINCT', 'Africa', 'Tropical forests', 'The dodo is so associated with extinction that gone the way of the dodo means something has completely disappeared.', 'The dodo was a flightless bird native to the island of Mauritius. Having evolved without natural predators it had no fear of humans which made it easy to hunt. It went extinct within 80 years of human contact.', 'https://images.unsplash.com/photo-1444464666168-49d633b86797?w=400&q=80', ''),

('Tasmanian Tiger', 'Thylacinus cynocephalus', 'Quoll', 'Holocene', 'EXTINCT', 'Australia', 'Forests and grasslands', 'The Tasmanian tiger could open its jaw almost 90 degrees wide far wider than any dog or wolf.', 'The Tasmanian tiger was a large carnivorous marsupial that looked like a dog with tiger stripes on its back. Despite its name it was not related to tigers or wolves but was a marsupial like kangaroos.', 'https://images.unsplash.com/photo-1474511320723-9a56873867b5?w=400&q=80', ''),

('Cave Lion', 'Panthera spelaea', 'African Lion', 'Pleistocene', 'EXTINCT', 'Eurasia', 'Caves and grasslands', 'Cave lions appeared in more prehistoric cave paintings than almost any other animal showing they were deeply feared.', 'The cave lion was one of the largest lions to ever exist about 10 percent bigger than modern African lions. It is depicted in prehistoric cave paintings showing how significant it was to early humans.', 'https://assets.iflscience.com/assets/articleNo/79909/aImg/84976/cave-lion-o.webp', ''),

('Giant Ground Sloth', 'Megatherium americanum', 'Modern Sloths', 'Pleistocene', 'EXTINCT', 'South America', 'Forests and grasslands', 'Despite being massive the giant ground sloth was an herbivore and used its enormous claws to pull down tree branches.', 'The giant ground sloth was the size of a modern elephant and one of the largest land mammals to ever exist. Unlike its tiny tree-dwelling relatives today it lived on the ground.', 'https://exhibits.museum.state.il.us/exhibits/larson/images/ia_sloth_reconstruction.gif', ''),

('Passenger Pigeon', 'Ectopistes migratorius', 'Mourning Dove', 'Holocene', 'EXTINCT', 'North America', 'Forests', 'Flocks of passenger pigeons were so enormous they could darken the sky for hours as they passed overhead.', 'The passenger pigeon was once the most abundant bird in North America with flocks so large they blocked out the sun for hours. Massive commercial hunting drove them from billions to zero in just decades.', 'https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=400&q=80', ''),

('Woolly Rhinoceros', 'Coelodonta antiquitatis', 'White Rhino, Black Rhino', 'Pleistocene', 'EXTINCT', 'Eurasia', 'Tundra and grasslands', 'The woolly rhinoceros front horn could grow over 3 feet long and was used to sweep snow aside to find food.', 'The woolly rhinoceros was a massive rhino covered in thick fur that roamed the ice age landscapes of Europe and Asia. It had two horns and is featured in prehistoric cave art.', 'https://images.unsplash.com/photo-1598300056393-4aac492f4344?w=400&q=80', ''),

('Terror Bird', 'Phorusrhacidae', 'Ostrich, Emu', 'Paleogene', 'EXTINCT', 'South America', 'Grasslands', 'Terror birds could run at speeds of up to 30 miles per hour making them terrifying pursuit predators.', 'Terror birds were massive flightless birds that were the apex predators of South America for millions of years. They could grow up to 10 feet tall and ran down prey with their huge hooked beak.', 'https://images.unsplash.com/photo-1557406272-fc759b3a1eb2?w=400&q=80', '');