INSERT INTO animals (name, scientific_name, common_name, status, period, cause_of_extinction, living_relative, habitat, continent, description, fun_fact, image_url, video_url) VALUES
('Dire Wolf', 'Aenocyon dirus', 'Dire Wolf', 'DE_EXTINCT', 'Pleistocene', 'Climate change and prey extinction', 'Gray Wolf, Domestic Dog', 'Forests and grasslands', 'North America', 'The dire wolf was one of the most iconic prehistoric predators. Larger and heavier than the modern gray wolf, it roamed North America in packs. In 2025 scientists announced successful de-extinction efforts.', 'The dire wolf was 25% heavier than a gray wolf and had a significantly stronger bite force built for crushing bone.', '', ''),

('Saber-tooth Cat', 'Smilodon fatalis', 'Saber-tooth Tiger', 'EXTINCT', 'Pleistocene', 'Climate change and overhunting', 'Lions, Tigers, House Cats', 'Grasslands and forests', 'North America', 'The saber-tooth cat was a fearsome predator known for its enormous canine teeth that could reach 11 inches long. It used these teeth to deliver killing bites to large prey.', 'Despite its nickname saber-tooth tiger, it was more closely related to modern lions than tigers.', '', ''),

('Woolly Mammoth', 'Mammuthus primigenius', 'Woolly Mammoth', 'EXTINCT', 'Pleistocene', 'Climate change and human hunting', 'African Elephant, Asian Elephant', 'Tundra and grasslands', 'Eurasia', 'The woolly mammoth was a massive elephant species covered in thick fur to survive the ice age. They lived alongside early humans who hunted them for food and used their bones for shelter.', 'Woolly mammoths had tusks that could grow up to 15 feet long and curved dramatically.', '', ''),

('Dodo', 'Raphus cucullatus', 'Dodo Bird', 'EXTINCT', 'Holocene', 'Hunting by humans and invasive species', 'Pigeons, Doves', 'Tropical forests', 'Africa', 'The dodo was a flightless bird native to the island of Mauritius. Having evolved without natural predators it had no fear of humans which made it easy to hunt. It went extinct within 80 years of human contact.', 'The dodo is so associated with extinction that the phrase gone the way of the dodo means something has completely disappeared.', '', ''),

('Tasmanian Tiger', 'Thylacinus cynocephalus', 'Thylacine', 'EXTINCT', 'Holocene', 'Hunting and habitat loss', 'Quoll', 'Forests and grasslands', 'Australia', 'The Tasmanian tiger was a large carnivorous marsupial that looked like a dog with tiger stripes on its back. Despite its name it was not related to tigers or wolves but was a marsupial like kangaroos.', 'The Tasmanian tiger could open its jaw almost 90 degrees wide — far wider than any dog or wolf.', '', ''),

('Cave Lion', 'Panthera spelaea', 'Cave Lion', 'EXTINCT', 'Pleistocene', 'Climate change and prey extinction', 'African Lion', 'Caves and grasslands', 'Eurasia', 'The cave lion was one of the largest lions to ever exist, about 10 percent bigger than modern African lions. It is depicted in prehistoric cave paintings showing how significant it was to early humans.', 'Cave lions appeared in more prehistoric cave paintings than almost any other animal showing they were deeply feared and respected.', '', ''),

('Giant Ground Sloth', 'Megatherium americanum', 'Megatherium', 'EXTINCT', 'Pleistocene', 'Human hunting and climate change', 'Modern Sloths', 'Forests and grasslands', 'South America', 'The giant ground sloth was the size of a modern elephant and one of the largest land mammals to ever exist. Unlike its tiny tree-dwelling relatives today it lived on the ground and could rear up on its hind legs to reach tall trees.', 'Despite being massive the giant ground sloth was an herbivore and used its enormous claws to pull down tree branches.', '', ''),

('Passenger Pigeon', 'Ectopistes migratorius', 'Passenger Pigeon', 'EXTINCT', 'Holocene', 'Mass hunting and habitat loss', 'Mourning Dove', 'Forests', 'North America', 'The passenger pigeon was once the most abundant bird in North America with flocks so large they blocked out the sun for hours. Massive commercial hunting drove them from billions to zero in just decades.', 'Flocks of passenger pigeons were so enormous they could darken the sky for hours as they passed overhead.', '', ''),

('Woolly Rhinoceros', 'Coelodonta antiquitatis', 'Woolly Rhino', 'EXTINCT', 'Pleistocene', 'Climate change and human hunting', 'White Rhino, Black Rhino', 'Tundra and grasslands', 'Eurasia', 'The woolly rhinoceros was a massive rhino covered in thick fur that roamed the ice age landscapes of Europe and Asia. It had two horns with the front one being enormous and it is featured in prehistoric cave art.', 'The woolly rhinoceros front horn could grow over 3 feet long and was likely used to sweep snow aside to find food.', '', ''),

('Terror Bird', 'Phorusrhacidae', 'Terror Bird', 'EXTINCT', 'Paleogene', 'Competition with new predators', 'Ostrich, Emu', 'Grasslands', 'South America', 'Terror birds were massive flightless birds that were the apex predators of South America for millions of years. They could grow up to 10 feet tall and ran down prey with powerful legs before finishing them with their huge hooked beak.', 'Terror birds could run at speeds of up to 30 miles per hour making them terrifying pursuit predators.', '', '');